### ISSUE TITLE
[FEATURE] offer `tmpfs`

### ISSUE THREAD

**Issue by andy108369** [ovrclk/provider-services#33]
Pods support `tmpfs`, some apps might benefit from this (for super fast writes & reads).
Akash should offer the `tmpfs` space rental, in the Pod that would look like this:

```
        volumeMounts:
        - mountPath: /mnt
          name: mnt-tmpfs-vol1
      volumes:
      - name: mnt-tmpfs-vol1
        emptyDir:
          medium: Memory
          sizeLimit: 100Gi
```
